name: llana

services:
    llana-test-prod-build-app:
        container_name: llana-test-prod-build-app
        build:
            context: .
            dockerfile: docker/images/base/Dockerfile
        ports:
            - "3000:3000"
        environment:
            DATABASE_URI: ${DATABASE_URI}
            JWT_KEY: ${JWT_KEY}
            HOSTS: ${HOSTS}
            SOFT_DELETE_COLUMN: ${SOFT_DELETE_COLUMN}